import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/pp.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';
import TransitionEffect from '@/components/TransitionEffect';
import profilePicture from "../../public/images/profile/pp1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Aziz | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="dark:text-light flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            {/* <div className="w-1/2 px-20 md:w-full">
              <Image
                src={profilePic}
                alt="Abdul Aziz"
                className="w-96 h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div> */}
            <div className="ml-20 md:ml-0 md:mb-8 dark:border-light dark:bg-dark relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8 lg:hidden md:inline-block">
              <div className="dark:bg-light absolute top-0 -right-4 -z-10 w-[104%] h-[103%] rounded-[2rem] bg-dark" />
              <Image
                src={profilePicture}
                alt="Abdul Aziz"
                className="w-full h-auto rounded-2xl"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="front-end developer."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Hi, Im Abdul Aziz, an informatics engineering student at
                Muhammadiyah University, Surakarta. Very enthusiastic in the
                world of technology, has a lot of experience in the field of web
                development, especially the front-end side, likes trying new
                things and experiences.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/CV-ABDUL AZIZ.pdf"
                  target={"_blank"}
                  className="dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light flex items-center bg-dark text-light p-2 px-6 text-lg font-semibold rounded-lg hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base"
                >
                  Resume <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="mailto:dulziz00@gmail.com"
                  target={"_blank"}
                  className="dark:text-light ml-4 text-lg font-medium capitalize text-dark underline md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        {/* <HireMe /> */}
        {/* <div className="absolute right-8 bottom-8 inline-block w-20">
          <Image
            src={lightBulb}
            alt="Abdul Aziz"
            className="w-full h-auto"
          ></Image>
        </div> */}
      </main>
    </>
  );
}
